### ISSUE TITLE
Should use fenrir.core and fenrir.utils python namespace, not  core and utils

### ISSUE THREAD

**Issue by sthibaul** [chrys87/fenrir#18]
Hello,

fenrir currently puts its core, utils, etc. modules right at the root of the python namespace, that's asking for clashing with other software :)

In Debian I have added the attached patch to fix this namespace issue.
[namespace.txt](https://github.com/chrys87/fenrir/files/1745537/namespace.txt)

Samuel

**Comment by chrys87** [comment]
Hi Samuel,
thanks for reporting and fixing this.
i will patch it upstream later today, after work.

cheers chrys

**Comment by chrys87** [comment]
it seems to make trouble for some users

chrys-home: Now that broke fenrir 1.5.
[jticket@starshine fenrir]$ sudo fenrir
Traceback (most recent call last):
  File "/usr/bin/fenrir", line 13, in <module>
    from fenrir.core import fenrirManager
ModuleNotFoundError: No module named 'fenrir'
[jticket@starshine fenrir]$

i need to fix this before i can push it.

**Comment by sthibaul** [comment]
Were the fenrir files really installed into a fenrir subdirectory, as the setup.py change should imply? Actually, I'm not sure how to understand what "broke fenrir 1.5" is supposed to mean. Did the user mix several versions of fenrir? Then it's not surprising that things go wrong.

**Comment by chrys87** [comment]
I will ask to clearify the situation.
i also will try it by myself. then i will push it.

**Comment by chrys87** [comment]
maybe he did try to run it from git tree directly. 
right this seems not to work anymore.
after installing it works. hmm

**Comment by sthibaul** [comment]
ah, the fenrir and fenrir-daemon scripts should be moved one directory higher for "from fenrir.core" to find the git files indeed.

**Comment by chrys87** [comment]
right.
I will do so on monday :). and reaply it then.

**Comment by chrys87** [comment]
ok, rust realized that "fenrir" needs to renamed since the module folder is already named "fenrir".
maybe fenrir.bin / fenrir-daemon.bin or something like that. its not most elegant but otherwhile the name of the folder and the application will collide. and it would be nice to be able to run it from git :). i have some users doing this. i think about. maybe i find a more elegant solution.

**Comment by chrys87** [comment]
Ok this issue is solved in an more complete way in master.
1. renamed "fenrir" to "fenrirscreenreader"
2. move fenrir and fenrir-daemon into its parant (so we still can execute it in git tree)
3. move /etc/fenrir (and all other references on file system to something like /etc/fenrirscreenreader
4. change install.sh, untinstall.sh, setup.py and other references to make it work.

so there is no conflict potential right now anymore.
since i plan to release an big update in the next couble of weeks and you already patched it for debian i will not backport it (its a bit of work).
