### ISSUE TITLE
fenrir and fenrir-pty causing major CPU and memory usage

### ISSUE THREAD

**Issue by lilmike** [chrys87/fenrir#40]
Fenrir-daemon and fenrir-pty, when running together, can cause major CPU and memory usage in the daemon when things like headphones are muted when using mumble or similar. Reproduced with linphone+fenrir-daemon+fenrir-pty+muting. Log is attached.
Best guess is that they are fighting for devices with one another/linphone/something else.
[fenrir.log](https://github.com/chrys87/fenrir/files/2321632/fenrir.log)

**Comment by chrys87** [comment]
What instance of fenrir does cause the CPU burn? does the deamon instance or an pty version go crazy?
how do you mute the system? pressing mute button on the wireless headset? or keyboard? (i ask because the headset is ignored by fenrir (daemon), the keybord not).

where do you press mute? in an TTY session or in an GUI? i assume in GUI since i do not see input events in the log. is that right?

Sadly i dont see the issue in the log. So i assume 1. the pty intance go crazy or 2. there is an endless loop somewhere what does not create an log output.

**Comment by chrys87** [comment]
Fixed in master.
"mute" key has multible lables (so it returns a list insteed of an string) i take care about this now. should be fixed for other keys too. like scrolllock (second name is coffee key loooool)
