### ISSUE TITLE
Phonetic reading is broken

### ISSUE THREAD

**Issue by Cleversn** [chrys87/fenrir#66]
Fenrir's phonetic reading is apparently broken. when I press for example fenrir_key+shift+2 to read the character phonetically, the review cursor jumps somewhere, usually to the next line. I've already made sure I'm using the correct keyboard layout, desktop.

Using the latest git version in Gentoo, on a pure console.

**Comment by lilmike** [comment]
Hiya,

It works here. Make sure to press and hold the keys in this order:
fenrir key, shift, numpad 2. If that doesn't work let me know, but I
notice that holding shift, then fenrir key does strange things myself.

-Michael.





On Wed, Jul 05, 2023 at 03:44:12PM -0700, Cleverson wrote:
>Fenrir's phonetic reading is apparently broken. when I press for example fenrir_key+shift+2 to read the character phonetically, the review cursor jumps somewhere, usually to the next line. I've already made sure I'm using the correct keyboard layout, desktop.
>
>Using the latest git version in Gentoo, on a pure console.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/chrys87/fenrir/issues/66
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>

-- 
Sorry about the test, it's just a me thing.
Michael Taboada, Creator of Games. Does that make me a god, well, sorta.
My pgp key: 79BC390E8864CD71305D4DD606CD2197A6EE5ED7
My website: https://michaels.world
2MB website: https://2mb.games
Don't believe everything you read on the internet. I might not be real, you might not be real, and this email certainly isn't real.
Sent from my internet connected...
stationary bicycle

**Comment by Cleversn** [comment]
Thanks Michael; indeed, it works the way you said. I suggest the developers make it work in any order you press the keys, or in case it is technically difficult, document that you must press in that order, since the user may have come from an environment where the order doesn't matter, e.g. Windows + the NVDA screen reader.

**Comment by chrys87** [comment]
fenrir needs to know what shortcut is used to interact with the screenreader. pressing any modifier first will result that the modifier key like ctrl or shift is already sent to the application you are currently working with. fenrir can sadly not predict the future (otherwhise i would not release it as open source but making a lot of money in the lottery >:-) ). so it can just behave correct when it knows just from the beginning that the shortcut you are going to press should not be forewarted because its ment to fenrir itself.
